CREATE TABLE IF NOT EXISTS purchase_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid VARCHAR(64) UNIQUE NOT NULL,
    item_uuid VARCHAR(64) NOT NULL,
    supplier_name VARCHAR(128) NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(64) NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(item_uuid) REFERENCES items(uuid) ON DELETE CASCADE
);
